version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_rs
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
